### ISSUE TITLE
PlantFragment 기능 개선

### ISSUE THREAD

**Issue by gunamkwon** [gunamkwon/SmartHydroponicsSystem_Refacotring#1]
### 기존 기능 및 UI

1. 2개의 Fragment를 이용하여 상단과 하단 UI 구성
2. 하단 Fragment 버튼에 따라 상단 식물 정보 변화

</br>

![image](https://user-images.githubusercontent.com/72553228/151179992-185dbaf4-1ba3-4904-92a8-4cfee8ba0112.png)

**Comment by gunamkwon** [comment]
### 현재
MainActivity를 TabLayout으로 구성 완료

### 목표 기능

- [x] PlantFragment를 하나로 합치고 ListView 구성
- [x] 원하는 식물 카드 구성에 따라 해당 식물정보 페이지로 이동

**Comment by gunamkwon** [comment]
### 목표 변경 사항

- [x] PlantFragment에 ListView 대신 RecyclerView로 구성

### 변경 이유

- CardView의 크기를 크게 만들 예정
- 이후 다른 식물 추가 시 스크롤 현상이 발생할 가능성 대비

**Comment by gunamkwon** [comment]
### Todo
- [x] MainActivity에서 TabLayout이랑 ViewPager랑 연결

**Comment by gunamkwon** [comment]
> ### 현재
> MainActivity를 TabLayout으로 구성 완료
> 
> ### 목표 기능
> * [x]  PlantFragment를 하나로 합치고 ListView 구성
> * [x]  원하는 식물 카드 구성에 따라 해당 식물정보 페이지로 이동
